services:
  koicareapi:
    image: ${DOCKER_REGISTRY-}koicareapi
    ports:
        - "5000:80"
        - "5001:443"
    build:
      context: .
      dockerfile: KoiCareApi/Dockerfile
    depends_on:
       - koicaredb
    environment:
       - ConnectionStrings_KoiCareDB=Server=192.168.1.10,1444;Database=KoiCareDB;User Id=sa;Password=KoiCareDB@123;TrustServerCertificate=True

  koicaredb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: koicaredb
    ports:
       - "1444:1433"
    volumes:
       - sql_data:/var/opt/mssql
    environment:
       - ACCEPT_EULA=Y
       - SA_PASSWORD=KoiCareDB@123
volumes:
  sql_data:
  
  
